remote_theme: pages-themes/cayman@v0.2.0
title: Notas del curso
author: Diego Gallegos Hern√°ndez a223214226
description: Todas las notas que he hecho del curso de inteligencia artificial impartido por el profesor Julio Waissman. El contenido esta conformado por apuntes de clase y extracciones del libro de Peter Norvig Artificial Intelligence: A modern approach. 





